# This is a basic workflow to help you get started with Actions

name: WF Hola Mundo en Java
run-name: Estoy aprendiendo Github Actions!
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Job called "run-java"
  run-java:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Instalar Java (puedes cambiar la versi√≥n si lo deseas)
      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: 17
          java-package: jdk

      # 3. Compilar HolaMundo.java
      - name: Compilar HolaMundo.java
        run: javac HolaMundo.java

      # 4. Ejecutar HolaMundo
      - name: Ejecutar HolaMundo
        run: java HolaMundo
